name: ElenaLipson
favicon: null
layout_spectrum: 0.19695
typography_spectrum: 0.58459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8b864c'
    - '#b9b694'
    - '#dad8c6'
    - '#f59fa4'
  brandStrength: 0.875
  lightness: 0.7505783084779978
  saturation: 0.30819872324354947
  rhythmicContrast: 0.8934559705667198
purpose: []
